apiVersion: v1
kind: Service
metadata:
  name: brimo-paylater-service
  namespace: default
spec:
  selector:
    app: brimo-pl-dev-lokal
  type: NodePort
  ports:
  - protocol: TCP
    port: 9192
    targetPort: 9192
