apiVersion: v1
kind: Service
metadata:
  name: {{ include "whitelist-ceria.fullname" . }}
  namespace: {{ .Values.image.namespace }}
  labels:
{{ include "whitelist-ceria.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} #http
      nodePort: {{ .Values.service.nodePort }} #New
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "whitelist-ceria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
